version: "3.9"

services:

  backend:
    build: ./backend
    ports:
      - "5000:5000"

  admin:
    build: ./admin
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    ports:
      - "3001:3000"